/** Svi UI stringovi na jednom mestu (srpski, latinica). */
export const STR = {
  appName: 'Porodično stablo',

  brand: {
    site: 'zabari.net',
    municipality: 'Opština Žabari',
    tagline: 'Mreža naše varoši',
  },

  nav: {
    tree: 'Porodice',
    birthdays: 'Rođendani',
    timeline: 'Vremenska linija',
    kinship: 'Srodstvo',
    gedcom: 'GEDCOM',
    settings: 'Podešavanja',
  },

  common: {
    save: 'Sačuvaj',
    cancel: 'Otkaži',
    delete: 'Obriši',
    edit: 'Izmeni',
    close: 'Zatvori',
    back: 'Nazad',
    add: 'Dodaj',
    loading: 'Učitavanje…',
    retry: 'Pokušaj ponovo',
    none: '— niko —',
    offlineDisabled: 'Nedostupno offline',
    notFound: 'Stranica nije pronađena.',
    backToTree: 'Nazad na stablo',
    error: 'Došlo je do greške.',
    underConstruction: 'U izradi…',
  },

  offline: {
    banner: 'Nema interneta — izmene su onemogućene',
  },

  readonly: {
    banner: 'Režim samo za pregled — izmene su onemogućene',
    loginToEdit: 'Prijavi se za izmene',
  },

  login: {
    title: 'Prijava',
    intro: 'Unesite porodičnu lozinku da biste pristupili stablu.',
    password: 'Lozinka',
    submit: 'Prijavi se',
    wrongPassword: 'Pogrešna lozinka',
  },

  session: {
    logout: 'Odjavi se',
    loggedOut: 'Odjavljeni ste.',
    authDisabled: 'Prijava je isključena (razvojni režim).',
    checkFailed: 'Server nije dostupan.',
  },

  tree: {
    emptyTitle: 'Stablo je prazno',
    emptyText: 'Počnite tako što ćete dodati prvu osobu u porodično stablo.',
    addFirstPerson: 'Dodaj prvu osobu',
    addPerson: 'Dodaj osobu',
    showInTree: 'Prikaži u stablu',
    showFromHere: 'Prikaži stablo odavde',
    families: 'Porodice',
    chooseFamily: 'Izaberite porodicu',
    familyLabel: 'Porodica',
    changeFamily: 'Promeni porodicu',
    members: 'članova',
    setFamilyHead: 'Postavi kao porodicu',
    unsetFamilyHead: 'Ukloni oznaku porodice',
    designatedBadge: 'loza',
    back: 'Prethodni pregled',
    loadFailed: 'Stablo nije moglo da se učita.',
    kinshipMode: 'Srodstvo',
    kinshipModeOn: 'Srodstvo: izaberi dve osobe',
    descendants: 'Generacije',
    depthMore: 'Više generacija potomaka',
    depthLess: 'Manje generacija potomaka',
  },

  search: {
    placeholder: 'Pretraži osobe…',
    noResults: 'Nema rezultata',
  },

  person: {
    newTitle: 'Nova osoba',
    newChildOf: 'Novo dete od',
    newSpouseOf: 'Novi supružnik za',
    newParentOf: 'Novi roditelj za',
    editTitle: 'Izmena osobe',
    notFound: 'Osoba nije pronađena.',
    firstName: 'Ime',
    lastName: 'Prezime',
    maidenName: 'Devojačko prezime',
    maidenShort: 'rođ.',
    gender: 'Pol',
    genderM: 'Muški',
    genderF: 'Ženski',
    genderU: 'Nepoznato',
    title: 'Titula',
    titlePlaceholder: 'dr, prof. dr, mr…',
    birthDate: 'Datum rođenja',
    deathDate: 'Datum smrti',
    datePlaceholder: 'DD.MM.GGGG, MM.GGGG ili GGGG',
    pickDate: 'Izaberi datum',
    birthPlace: 'Mesto rođenja',
    notes: 'Beleške',
    father: 'Otac',
    mother: 'Majka',
    parents: 'Roditelji',
    siblings: 'Braća i sestre',
    unions: 'Brakovi i partnerstva',
    children: 'Deca',
    halfPaternal: 'po ocu',
    halfMaternal: 'po majci',
    addChild: 'Dodaj dete',
    addSpouse: 'Dodaj supružnika',
    addParent: 'Dodaj roditelja',
    deleteConfirmTitle: 'Obriši osobu?',
    deleteConfirmText:
      'Ova radnja je trajna. Veze ka deci će biti uklonjene, a brakovi ove osobe obrisani.',
    created: 'Osoba je dodata.',
    updated: 'Izmene su sačuvane.',
    deleted: 'Osoba je obrisana.',
    pickerSearch: 'Pretraži…',
  },

  union: {
    editTitle: 'Izmena braka',
    type: 'Tip',
    typeMarriage: 'Brak',
    typePartnership: 'Partnerstvo',
    startDate: 'Datum venčanja',
    endDate: 'Kraj braka',
    endReason: 'Razlog kraja',
    endReasonNone: '—',
    endReasonDivorce: 'Razvod',
    endReasonDeath: 'Smrt',
    endReasonSeparation: 'Razdvajanje',
    deleteConfirmTitle: 'Obriši brak?',
    deleteConfirmText: 'Brak/partnerstvo će biti trajno obrisano. Osobe ostaju u stablu.',
    created: 'Brak je dodat.',
    updated: 'Brak je izmenjen.',
    deleted: 'Brak je obrisan.',
    unknownPartner: '(obrisana osoba)',
  },

  photo: {
    dialogTitle: 'Fotografija osobe',
    pick: 'Izaberi sliku',
    change: 'Promeni sliku',
    remove: 'Ukloni sliku',
    zoom: 'Uvećanje',
    upload: 'Sačuvaj sliku',
    uploaded: 'Slika je sačuvana.',
    removed: 'Slika je uklonjena.',
    hint: 'Pomerite i uvećajte sliku — biće isečena u krug.',
    saveFirst: 'Sačuvajte osobu, pa zatim dodajte sliku.',
  },

  settings: {
    title: 'Podešavanja',
    theme: 'Tema',
    themeLight: 'Svetla',
    themeDark: 'Tamna',
    themeSystem: 'Sistemska',
    install: 'Instalacija',
    installButton: 'Instaliraj aplikaciju',
    installHint:
      'Aplikaciju možete instalirati na početni ekran telefona ili računara i koristiti je kao zasebnu aplikaciju.',
    installUnavailable: 'Instalacija trenutno nije dostupna — aplikacija je možda već instalirana.',
    installAndroidTitle: 'Uputstvo za Android',
    installAndroid1: 'Otvorite sajt u Chrome pregledaču.',
    installAndroid2: 'Dodirnite meni (⋮) gore desno.',
    installAndroid3: 'Izaberite „Instaliraj aplikaciju" ili „Dodaj na početni ekran".',
    installIosTitle: 'Uputstvo za iPhone/iPad',
    installIos1: 'Otvorite sajt u Safari pregledaču.',
    installIos2: 'Dodirnite dugme „Share" (kvadrat sa strelicom nagore).',
    installIos3: 'Izaberite „Add to Home Screen" („Dodaj na početni ekran").',
    sessionSection: 'Sesija',
    account: 'Nalog',
    authDisabledNote: 'Prijava je isključena u dev modu.',
    readonlyNote: 'Prijavljeni ste u režimu samo za pregled. Izmene nisu dozvoljene.',
    dataSection: 'Podaci',
    personsCount: 'Osoba u stablu',
    unionsCount: 'Brakova i partnerstava',
    gedcomLink: 'Uvoz i izvoz podataka (GEDCOM)',
    posterSection: 'Izvoz postera',
    posterHint: 'Napravite poster porodičnog stabla za štampu ili čuvanje kao PDF.',
    posterLink: 'Štampa / PDF poster',
  },

  poster: {
    kicker: 'PODEŠAVANJA · IZVOZ',
    title: 'Štampa / PDF poster',
    intro: 'Napravite poster porodičnog stabla spreman za štampu ili čuvanje kao PDF.',
    scopeSection: 'Šta se izvozi?',
    scopeView: 'Trenutni prikaz stabla',
    scopeLineage: 'Cela loza',
    scopeAncestors: 'Samo preci',
    scopeDescendants: 'Samo potomci',
    scopeSelected: 'Izabrani čvorovi',
    scopeKinship: 'Veza srodstva',
    scopeViewHint: 'Izvozi ono što se prikazuje na ekranu — fokus i broj generacija potomaka.',
    scopeLineageHint: 'Cela izabrana porodica — onako kako se prikazuje u stablu.',
    scopeAncestorsHint: 'Samo preci glavne osobe, sve do najstarijih.',
    scopeDescendantsHint: 'Samo potomci glavne osobe (sa supružnicima).',
    scopeSelectedHint: 'Kliknite kartice u pregledu da izaberete osobe — štampa se samo izabrano.',
    scopeKinshipHint: 'Izvozi rezultat opcije „Prikaži vezu" iz kalkulatora srodstva.',
    generationsLabel: 'Generacije potomaka',
    pickModeBadge: 'Izbor čvorova',
    previewBadge: 'Pregled postera',
    pickModeHint: 'Klik = izbor · točkić = zum · prevlačenje = pomeranje',
    selectedCount: 'izabrano',
    selectionEmpty: 'Kliknite kartice u pregledu da izaberete osobe za poster.',
    selectionDisconnected:
      'Neke izabrane osobe nisu povezane sa prvom izabranom, pa se ne prikazuju na posteru.',
    clearSelection: 'Očisti izbor',
    kinshipMissing: 'Izaberite dve različite osobe da biste dobili vezu srodstva.',
    kinshipUnavailable: 'Za ovu vezu nema prikaza u stablu.',
    kinshipLineLabel: 'Linija srodstva',
    legendSelected: 'Izabrano',
    legendKinship: 'Veza srodstva',
    posterButton: 'Poster',
    familyLabel: 'Porodica',
    mainPersonLabel: 'Glavna osoba',
    formatSection: 'Format',
    paperSize: 'VELIČINA PAPIRA',
    paperTiling: 'Više A4',
    paperTilingLabel: '4 × A4 (za lepljenje)',
    orientation: 'ORIJENTACIJA',
    orientPortrait: 'Uspravno',
    orientLandscape: 'Položeno',
    contentSection: 'Sadržaj kartice',
    contentPhotos: 'Fotografije',
    contentYears: 'Godine života',
    contentTitle: 'Titula',
    contentBirthplace: 'Mesto rođenja',
    contentGenderColors: 'Boje pola',
    extrasSection: 'Elementi postera',
    extraTitle: 'Naslov',
    extraSubtitle: 'Podnaslov i datum',
    extraLegend: 'Legenda',
    extraFrame: 'Dekorativni okvir',
    extraWatermark: 'Vodeni žig',
    titleLabel: 'Tekst naslova',
    downloadPdf: 'Preuzmi PDF',
    print: 'Štampaj',
    pdfHint: 'U dijalogu štampe izaberite „Sačuvaj kao PDF" kao odredište.',
    subtitlePrefix: 'Izvezeno',
    personsWord: 'osoba',
    legendMale: 'Muški',
    legendFemale: 'Ženski',
    legendMain: 'Glavna osoba',
    emptyTree: 'Stablo je prazno — nema šta da se izveze.',
    defaultTitlePrefix: 'Porodica',
  },

  birthdays: {
    birthdaysTitle: 'Rođendani',
    anniversariesTitle: 'Godišnjice braka',
    today: 'Danas! 🎂',
    tomorrow: 'Sutra',
    emptyBirthdays: 'Nema žive osobe sa punim datumom rođenja.',
    emptyAnniversaries: 'Nema aktivnih brakova sa punim datumom venčanja.',
    fullDateNote: 'Prikazuju se samo osobe sa punim datumom rođenja.',
    marriageSuffix: 'braka',
  },

  timeline: {
    birth: 'Rođenje',
    marriage: 'Venčanje',
    partnership: 'Partnerstvo',
    divorce: 'Razvod',
    death: 'Smrt',
    empty: 'Nema događaja sa datumima.',
  },

  kinship: {
    title: 'Kalkulator srodstva',
    personA: 'Osoba A',
    personB: 'Osoba B',
    swap: 'Zameni osobe',
    pickBoth: 'Izaberite dve osobe da biste videli njihovo srodstvo.',
    samePerson: 'Izabrana je ista osoba — izaberite dve različite.',
    degreeSuffix: 'koleno',
    pathLabel: 'Putanja srodstva',
    commonAncestor: 'Zajednički predak',
    error: 'Srodstvo nije moglo da se izračuna.',
    selectFirst: 'Izaberite prvu osobu u stablu.',
    selectSecond: 'Izaberite još jednu osobu.',
    openCalculator: 'Otvori kalkulator',
    clear: 'Očisti',
    showConnection: 'Prikaži vezu',
    connectionTitle: 'Veza srodstva',
    connectionMissing: 'Izaberite dve osobe u kalkulatoru da biste prikazali vezu.',
    connectionUnavailable: 'Za ovu vezu nema prikaza u stablu.',
    backToCalculator: 'Nazad na kalkulator',
    /** Dvostruko/višestruko srodstvo. */
    multiNote: 'U srodstvu su po više linija — izaberite koju vezu da prikažete.',
    lineWord: 'linija',
    via: 'preko',
  },

  gedcom: {
    exportTitle: 'Izvoz',
    exportText:
      'Preuzmite celo stablo kao GEDCOM 5.5.1 fajl (.ged) — standardni format za razmenu rodoslovnih podataka.',
    exportButton: 'Preuzmi .ged fajl',
    exportFailed: 'Izvoz nije uspeo.',
    importTitle: 'Uvoz',
    fileLabel: 'GEDCOM fajl (.ged)',
    modeLabel: 'Režim uvoza',
    modeReplace: 'Zameni sve',
    modeReplaceWarning: 'Briše SVE postojeće osobe, brakove i slike pre uvoza. Radnja je nepovratna.',
    modeMerge: 'Dodaj nove',
    modeMergeHint: 'Postojeće osobe se uparuju po GEDCOM oznaci, nove se dodaju.',
    dryRunButton: 'Proveri (probni uvoz)',
    importButton: 'Uvezi',
    confirmReplaceTitle: 'Zameni sve podatke?',
    confirmReplaceText:
      'Uvoz će obrisati sve postojeće osobe, brakove i slike i zameniti ih sadržajem fajla. Ovo ne može da se opozove.',
    confirmReplaceLabel: 'Zameni i uvezi',
    resultDryRunTitle: 'Rezultat probnog uvoza',
    resultTitle: 'Rezultat uvoza',
    personsCreated: 'Novih osoba',
    unionsCreated: 'Novih brakova',
    matched: 'Uparenih postojećih',
    warningsTitle: 'Upozorenja',
    warningTag: 'GEDCOM tag',
    warningCount: 'Broj',
    warningSample: 'Primer',
    noWarnings: 'Bez upozorenja — svi podaci su podržani.',
    imported: 'Uvoz je završen.',
    dryRunDone: 'Probni uvoz je završen — ništa nije upisano.',
  },

  backup: {
    title: 'Potpuna rezervna kopija',
    intro:
      'ZIP sa celom bazom i svim slikama — tačan snimak za vraćanje. Za razliku od GEDCOM-a, uključuje slike i sva interna polja. Dostupno samo administratoru.',
    exportButton: 'Preuzmi rezervnu kopiju (ZIP)',
    exportFailed: 'Izrada rezervne kopije nije uspela.',
    restoreTitle: 'Vraćanje iz kopije',
    restoreHint: 'Učitajte ranije preuzeti ZIP. Ovo BRIŠE sve postojeće osobe, brakove i slike i zamenjuje ih sadržajem kopije.',
    fileLabel: 'Fajl rezervne kopije (.zip)',
    restoreButton: 'Vrati iz kopije',
    confirmTitle: 'Vratiti iz rezervne kopije?',
    confirmText:
      'Vraćanje će obrisati sve trenutne podatke i slike i zameniti ih sadržajem ZIP fajla. Ovo ne može da se opozove.',
    confirmLabel: 'Obriši i vrati',
    restored: 'Vraćanje je završeno.',
    restoreFailed: 'Vraćanje nije uspelo.',
    resultTitle: 'Rezultat vraćanja',
    personsRestored: 'Vraćeno osoba',
    unionsRestored: 'Vraćeno brakova',
    photosRestored: 'Vraćeno slika',
  },

  errors: {
    unauthorized: 'Niste prijavljeni.',
    generic: 'Greška u komunikaciji sa serverom.',
  },
} as const;
