/** Svi UI stringovi na jednom mestu (srpski, latinica). */
export const STR = {
  appName: 'Porodično stablo',

  nav: {
    tree: 'Stablo',
    birthdays: 'Rođendani',
    timeline: 'Vremenska linija',
    kinship: 'Srodstvo',
    gedcom: 'GEDCOM',
    settings: 'Podešavanja',
  },

  common: {
    save: 'Sačuvaj',
    cancel: 'Otkaži',
    delete: 'Obriši',
    edit: 'Izmeni',
    close: 'Zatvori',
    back: 'Nazad',
    add: 'Dodaj',
    loading: 'Učitavanje…',
    retry: 'Pokušaj ponovo',
    none: '— niko —',
    offlineDisabled: 'Nedostupno offline',
    notFound: 'Stranica nije pronađena.',
    backToTree: 'Nazad na stablo',
    error: 'Došlo je do greške.',
    underConstruction: 'U izradi…',
  },

  offline: {
    banner: 'Nema interneta — izmene su onemogućene',
  },

  login: {
    title: 'Prijava',
    intro: 'Unesite porodičnu lozinku da biste pristupili stablu.',
    password: 'Lozinka',
    submit: 'Prijavi se',
    wrongPassword: 'Pogrešna lozinka',
  },

  session: {
    logout: 'Odjavi se',
    loggedOut: 'Odjavljeni ste.',
    authDisabled: 'Prijava je isključena (razvojni režim).',
    checkFailed: 'Server nije dostupan.',
  },

  tree: {
    emptyTitle: 'Stablo je prazno',
    emptyText: 'Počnite tako što ćete dodati prvu osobu u porodično stablo.',
    addFirstPerson: 'Dodaj prvu osobu',
    addPerson: 'Dodaj osobu',
    showInTree: 'Prikaži u stablu',
    loadFailed: 'Stablo nije moglo da se učita.',
  },

  search: {
    placeholder: 'Pretraži osobe…',
    noResults: 'Nema rezultata',
  },

  person: {
    newTitle: 'Nova osoba',
    editTitle: 'Izmena osobe',
    notFound: 'Osoba nije pronađena.',
    firstName: 'Ime',
    lastName: 'Prezime',
    maidenName: 'Devojačko prezime',
    maidenShort: 'rođ.',
    gender: 'Pol',
    genderM: 'Muški',
    genderF: 'Ženski',
    genderU: 'Nepoznato',
    title: 'Titula',
    titlePlaceholder: 'dr, prof. dr, mr…',
    birthDate: 'Datum rođenja',
    deathDate: 'Datum smrti',
    datePlaceholder: 'YYYY-MM-DD, YYYY-MM ili YYYY',
    birthPlace: 'Mesto rođenja',
    notes: 'Beleške',
    father: 'Otac',
    mother: 'Majka',
    parents: 'Roditelji',
    siblings: 'Braća i sestre',
    unions: 'Brakovi i partnerstva',
    children: 'Deca',
    halfPaternal: 'po ocu',
    halfMaternal: 'po majci',
    addChild: 'Dodaj dete',
    addSpouse: 'Dodaj supružnika',
    addParent: 'Dodaj roditelja',
    deleteConfirmTitle: 'Obriši osobu?',
    deleteConfirmText:
      'Ova radnja je trajna. Veze ka deci će biti uklonjene, a brakovi ove osobe obrisani.',
    created: 'Osoba je dodata.',
    updated: 'Izmene su sačuvane.',
    deleted: 'Osoba je obrisana.',
    pickerSearch: 'Pretraži…',
  },

  union: {
    editTitle: 'Izmena braka',
    type: 'Tip',
    typeMarriage: 'Brak',
    typePartnership: 'Partnerstvo',
    startDate: 'Datum venčanja',
    endDate: 'Kraj braka',
    endReason: 'Razlog kraja',
    endReasonNone: '—',
    endReasonDivorce: 'Razvod',
    endReasonDeath: 'Smrt',
    endReasonSeparation: 'Razdvajanje',
    deleteConfirmTitle: 'Obriši brak?',
    deleteConfirmText: 'Brak/partnerstvo će biti trajno obrisano. Osobe ostaju u stablu.',
    created: 'Brak je dodat.',
    updated: 'Brak je izmenjen.',
    deleted: 'Brak je obrisan.',
    unknownPartner: '(obrisana osoba)',
  },

  photo: {
    dialogTitle: 'Fotografija osobe',
    pick: 'Izaberi sliku',
    change: 'Promeni sliku',
    remove: 'Ukloni sliku',
    zoom: 'Uvećanje',
    upload: 'Sačuvaj sliku',
    uploaded: 'Slika je sačuvana.',
    removed: 'Slika je uklonjena.',
    hint: 'Pomerite i uvećajte sliku — biće isečena u krug.',
    saveFirst: 'Sačuvajte osobu, pa zatim dodajte sliku.',
  },

  settings: {
    title: 'Podešavanja',
    theme: 'Tema',
    themeLight: 'Svetla',
    themeDark: 'Tamna',
    themeSystem: 'Sistemska',
    install: 'Instalacija',
    installButton: 'Instaliraj aplikaciju',
    installHint:
      'Aplikaciju možete instalirati na početni ekran. Na iPhone-u: Share → „Add to Home Screen".',
    installUnavailable: 'Instalacija trenutno nije dostupna — aplikacija je možda već instalirana.',
    installIosTitle: 'Uputstvo za iPhone/iPad',
    installIos1: 'Otvorite sajt u Safari pregledaču.',
    installIos2: 'Dodirnite dugme „Share" (kvadrat sa strelicom nagore).',
    installIos3: 'Izaberite „Add to Home Screen" („Dodaj na početni ekran").',
    sessionSection: 'Sesija',
    account: 'Nalog',
    authDisabledNote: 'Prijava je isključena u dev modu.',
    dataSection: 'Podaci',
    personsCount: 'Osoba u stablu',
    unionsCount: 'Brakova i partnerstava',
    gedcomLink: 'Uvoz i izvoz podataka (GEDCOM)',
  },

  birthdays: {
    birthdaysTitle: 'Rođendani',
    anniversariesTitle: 'Godišnjice braka',
    today: 'Danas! 🎂',
    tomorrow: 'Sutra',
    emptyBirthdays: 'Nema žive osobe sa punim datumom rođenja.',
    emptyAnniversaries: 'Nema aktivnih brakova sa punim datumom venčanja.',
    fullDateNote: 'Prikazuju se samo osobe sa punim datumom rođenja.',
    marriageSuffix: 'braka',
  },

  timeline: {
    birth: 'Rođenje',
    marriage: 'Venčanje',
    partnership: 'Partnerstvo',
    divorce: 'Razvod',
    death: 'Smrt',
    empty: 'Nema događaja sa datumima.',
  },

  kinship: {
    title: 'Kalkulator srodstva',
    personA: 'Osoba A',
    personB: 'Osoba B',
    swap: 'Zameni osobe',
    pickBoth: 'Izaberite dve osobe da biste videli njihovo srodstvo.',
    samePerson: 'Izabrana je ista osoba — izaberite dve različite.',
    degreeSuffix: 'koleno',
    pathLabel: 'Putanja srodstva',
    error: 'Srodstvo nije moglo da se izračuna.',
  },

  gedcom: {
    exportTitle: 'Izvoz',
    exportText:
      'Preuzmite celo stablo kao GEDCOM 5.5.1 fajl (.ged) — standardni format za razmenu rodoslovnih podataka.',
    exportButton: 'Preuzmi .ged fajl',
    exportFailed: 'Izvoz nije uspeo.',
    importTitle: 'Uvoz',
    fileLabel: 'GEDCOM fajl (.ged)',
    modeLabel: 'Režim uvoza',
    modeReplace: 'Zameni sve',
    modeReplaceWarning: 'Briše SVE postojeće osobe, brakove i slike pre uvoza. Radnja je nepovratna.',
    modeMerge: 'Dodaj nove',
    modeMergeHint: 'Postojeće osobe se uparuju po GEDCOM oznaci, nove se dodaju.',
    dryRunButton: 'Proveri (probni uvoz)',
    importButton: 'Uvezi',
    confirmReplaceTitle: 'Zameni sve podatke?',
    confirmReplaceText:
      'Uvoz će obrisati sve postojeće osobe, brakove i slike i zameniti ih sadržajem fajla. Ovo ne može da se opozove.',
    confirmReplaceLabel: 'Zameni i uvezi',
    resultDryRunTitle: 'Rezultat probnog uvoza',
    resultTitle: 'Rezultat uvoza',
    personsCreated: 'Novih osoba',
    unionsCreated: 'Novih brakova',
    matched: 'Uparenih postojećih',
    warningsTitle: 'Upozorenja',
    warningTag: 'GEDCOM tag',
    warningCount: 'Broj',
    warningSample: 'Primer',
    noWarnings: 'Bez upozorenja — svi podaci su podržani.',
    imported: 'Uvoz je završen.',
    dryRunDone: 'Probni uvoz je završen — ništa nije upisano.',
  },

  errors: {
    unauthorized: 'Niste prijavljeni.',
    generic: 'Greška u komunikaciji sa serverom.',
  },
} as const;
