/** Svi UI stringovi na jednom mestu (srpski, latinica). */
export const STR = {
  appName: 'Porodično stablo',

  brand: {
    site: 'zabari.net',
    municipality: 'Opština Žabari',
    tagline: 'Mreža naše varoši',
  },

  nav: {
    tree: 'Porodice',
    birthdays: 'Rođendani',
    timeline: 'Vremenska linija',
    kinship: 'Srodstvo',
    gedcom: 'GEDCOM',
    settings: 'Podešavanja',
  },

  common: {
    save: 'Sačuvaj',
    cancel: 'Otkaži',
    delete: 'Obriši',
    edit: 'Izmeni',
    close: 'Zatvori',
    back: 'Nazad',
    add: 'Dodaj',
    loading: 'Učitavanje…',
    retry: 'Pokušaj ponovo',
    none: '— niko —',
    offlineDisabled: 'Nedostupno offline',
    notFound: 'Stranica nije pronađena.',
    backToTree: 'Nazad na stablo',
    error: 'Došlo je do greške.',
    underConstruction: 'U izradi…',
  },

  offline: {
    banner: 'Nema interneta — izmene su onemogućene',
  },

  readonly: {
    banner: 'Režim samo za pregled — izmene su onemogućene',
    loginToEdit: 'Prijavi se za izmene',
  },

  login: {
    title: 'Prijava',
    intro: 'Unesite porodičnu lozinku da biste pristupili stablu.',
    password: 'Lozinka',
    submit: 'Prijavi se',
    wrongPassword: 'Pogrešna lozinka',
  },

  session: {
    logout: 'Odjavi se',
    loggedOut: 'Odjavljeni ste.',
    authDisabled: 'Prijava je isključena (razvojni režim).',
    checkFailed: 'Server nije dostupan.',
  },

  tree: {
    emptyTitle: 'Stablo je prazno',
    emptyText: 'Počnite tako što ćete dodati prvu osobu u porodično stablo.',
    addFirstPerson: 'Dodaj prvu osobu',
    addPerson: 'Dodaj osobu',
    showInTree: 'Prikaži u stablu',
    editPerson: 'Izmeni osobu',
    hideBranch: 'Sakrij ovu granu',
    hideNote: 'Glavna osoba i preci se ne skrivaju',
    hiddenCount: 'Sakriveno:',
    showAll: 'Prikaži sve',
    restoreBranch: 'Vrati u prikaz',
    allRestored: 'Sve grane su vraćene u prikaz',
    hint: 'Desni klik na karticu = meni · dugi pritisak na telefonu · „−" na kartici sakriva granu',
    showFromHere: 'Prikaži stablo odavde',
    families: 'Porodice',
    chooseFamily: 'Izaberite porodicu',
    familyLabel: 'Porodica',
    changeFamily: 'Promeni porodicu',
    members: 'članova',
    setFamilyHead: 'Postavi kao porodicu',
    unsetFamilyHead: 'Ukloni oznaku porodice',
    designatedBadge: 'loza',
    back: 'Prethodni pregled',
    loadFailed: 'Stablo nije moglo da se učita.',
    kinshipMode: 'Srodstvo',
    kinshipModeOn: 'Srodstvo: izaberi dve osobe',
    descendants: 'Generacije',
    depthMore: 'Više generacija potomaka',
    depthLess: 'Manje generacija potomaka',
  },

  search: {
    placeholder: 'Pretraži osobe…',
    noResults: 'Nema rezultata',
  },

  person: {
    newTitle: 'Nova osoba',
    newChildOf: 'Novo dete od',
    newSpouseOf: 'Novi supružnik za',
    newParentOf: 'Novi roditelj za',
    editTitle: 'Izmena osobe',
    notFound: 'Osoba nije pronađena.',
    firstName: 'Ime',
    lastName: 'Prezime',
    maidenName: 'Devojačko prezime',
    maidenShort: 'rođ.',
    gender: 'Pol',
    genderM: 'Muški',
    genderF: 'Ženski',
    genderU: 'Nepoznato',
    title: 'Titula',
    titlePlaceholder: 'dr, prof. dr, mr…',
    birthDate: 'Datum rođenja',
    deathDate: 'Datum smrti',
    datePlaceholder: 'DD.MM.GGGG, MM.GGGG ili GGGG',
    pickDate: 'Izaberi datum',
    birthPlace: 'Mesto rođenja',
    notes: 'Beleške',
    father: 'Otac',
    mother: 'Majka',
    parents: 'Roditelji',
    siblings: 'Braća i sestre',
    unions: 'Brakovi i partnerstva',
    children: 'Deca',
    halfPaternal: 'po ocu',
    halfMaternal: 'po majci',
    addChild: 'Dodaj dete',
    addSpouse: 'Dodaj supružnika',
    addExistingSpouse: 'Dodaj postojećeg supružnika',
    addParent: 'Dodaj roditelja',
    deleteConfirmTitle: 'Obriši osobu?',
    deleteConfirmText:
      'Ova radnja je trajna. Veze ka deci će biti uklonjene, a brakovi ove osobe obrisani.',
    created: 'Osoba je dodata.',
    updated: 'Izmene su sačuvane.',
    deleted: 'Osoba je obrisana.',
    pickerSearch: 'Pretraži…',
  },

  union: {
    addTitle: 'Dodaj supružnika',
    editTitle: 'Izmena braka',
    existingPersonTab: 'Postojeća osoba iz stabla',
    newPersonTab: 'Nova osoba',
    partnerField: 'Izaberi supružnika / partnera',
    newPersonPrompt: 'Otvoriće se forma za unos nove osobe koja će automatski biti dodata kao supružnik.',
    linkButton: 'Poveži supružnika',
    newPersonButton: 'Pređi na unos nove osobe',
    type: 'Tip',
    typeMarriage: 'Brak',
    typePartnership: 'Partnerstvo',
    startDate: 'Datum venčanja',
    endDate: 'Kraj braka',
    endReason: 'Razlog kraja',
    endReasonNone: '—',
    endReasonDivorce: 'Razvod',
    endReasonDeath: 'Smrt',
    endReasonSeparation: 'Razdvajanje',
    deleteConfirmTitle: 'Obriši brak?',
    deleteConfirmText: 'Brak/partnerstvo će biti trajno obrisano. Osobe ostaju u stablu.',
    created: 'Brak je dodat.',
    updated: 'Brak je izmenjen.',
    deleted: 'Brak je obrisan.',
    unknownPartner: '(obrisana osoba)',
  },

  photo: {
    dialogTitle: 'Fotografija osobe',
    pick: 'Izaberi sliku',
    change: 'Promeni sliku',
    remove: 'Ukloni sliku',
    zoom: 'Uvećanje',
    upload: 'Sačuvaj sliku',
    uploaded: 'Slika je sačuvana.',
    removed: 'Slika je uklonjena.',
    hint: 'Pomerite i uvećajte sliku — biće isečena u krug.',
    saveFirst: 'Sačuvajte osobu, pa zatim dodajte sliku.',
  },

  settings: {
    title: 'Podešavanja',
    theme: 'Tema',
    themeLight: 'Svetla',
    themeDark: 'Tamna',
    themeSystem: 'Sistemska',
    install: 'Instalacija',
    installButton: 'Instaliraj aplikaciju',
    installHint:
      'Aplikaciju možete instalirati na početni ekran telefona ili računara i koristiti je kao zasebnu aplikaciju.',
    installUnavailable: 'Instalacija trenutno nije dostupna — aplikacija je možda već instalirana.',
    installAndroidTitle: 'Uputstvo za Android',
    installAndroid1: 'Otvorite sajt u Chrome pregledaču.',
    installAndroid2: 'Dodirnite meni (⋮) gore desno.',
    installAndroid3: 'Izaberite „Instaliraj aplikaciju" ili „Dodaj na početni ekran".',
    installIosTitle: 'Uputstvo za iPhone/iPad',
    installIos1: 'Otvorite sajt u Safari pregledaču.',
    installIos2: 'Dodirnite dugme „Share" (kvadrat sa strelicom nagore).',
    installIos3: 'Izaberite „Add to Home Screen" („Dodaj na početni ekran").',
    sessionSection: 'Sesija',
    account: 'Nalog',
    authDisabledNote: 'Prijava je isključena u dev modu.',
    readonlyNote: 'Prijavljeni ste u režimu samo za pregled. Izmene nisu dozvoljene.',
    dataSection: 'Podaci',
    personsCount: 'Osoba u stablu',
    unionsCount: 'Brakova i partnerstava',
    gedcomLink: 'Uvoz i izvoz podataka (GEDCOM)',
    posterSection: 'Izvoz postera',
    posterHint: 'Napravite poster porodičnog stabla za štampu ili čuvanje kao PDF.',
    posterLink: 'Štampa / PDF poster',
    kinshipSection: 'Računanje srodstva',
    kinshipHint: 'Izaberite način računanja stepena krvnog srodstva koji se koristi u kalkulatoru i stablu.',
  },

  poster: {
    kicker: 'PODEŠAVANJA · IZVOZ',
    title: 'Štampa / PDF poster',
    intro: 'Napravite poster porodičnog stabla spreman za štampu ili čuvanje kao PDF.',
    scopeSection: 'Šta se izvozi?',
    scopeView: 'Trenutni prikaz stabla',
    scopeLineage: 'Cela loza',
    scopeAncestors: 'Samo preci',
    scopeDescendants: 'Samo potomci',
    scopeSelected: 'Izabrani čvorovi',
    scopeKinship: 'Veza srodstva',
    scopeViewHint: 'Izvozi ono što se prikazuje na ekranu — fokus i broj generacija potomaka.',
    scopeLineageHint: 'Cela izabrana porodica — onako kako se prikazuje u stablu.',
    scopeAncestorsHint: 'Samo preci glavne osobe, sve do najstarijih.',
    scopeDescendantsHint: 'Samo potomci glavne osobe (sa supružnicima).',
    scopeSelectedHint: 'Kliknite kartice u pregledu da izaberete osobe — štampa se samo izabrano.',
    scopeKinshipHint: 'Izvozi rezultat opcije „Prikaži vezu" iz kalkulatora srodstva.',
    generationsLabel: 'Generacije potomaka',
    pickModeBadge: 'Izbor čvorova',
    previewBadge: 'Pregled postera',
    pickModeHint: 'Klik = izbor · točkić = zum · prevlačenje = pomeranje',
    selectedCount: 'izabrano',
    selectionEmpty: 'Kliknite kartice u pregledu da izaberete osobe za poster.',
    selectionDisconnected:
      'Neke izabrane osobe nisu povezane sa prvom izabranom, pa se ne prikazuju na posteru.',
    clearSelection: 'Očisti izbor',
    kinshipMissing: 'Izaberite dve različite osobe da biste dobili vezu srodstva.',
    kinshipUnavailable: 'Za ovu vezu nema prikaza u stablu.',
    kinshipLineLabel: 'Linija srodstva',
    legendSelected: 'Izabrano',
    legendKinship: 'Veza srodstva',
    posterButton: 'Poster',
    familyLabel: 'Porodica',
    mainPersonLabel: 'Glavna osoba',
    formatSection: 'Format',
    paperSize: 'VELIČINA PAPIRA',
    paperTiling: 'Više A4',
    paperTilingLabel: '4 × A4 (za lepljenje)',
    orientation: 'ORIJENTACIJA',
    orientPortrait: 'Uspravno',
    orientLandscape: 'Položeno',
    contentSection: 'Sadržaj kartice',
    contentPhotos: 'Fotografije',
    contentYears: 'Godine života',
    contentTitle: 'Titula',
    contentBirthplace: 'Mesto rođenja',
    contentGenderColors: 'Boje pola',
    extrasSection: 'Elementi postera',
    extraTitle: 'Naslov',
    extraSubtitle: 'Podnaslov i datum',
    extraLegend: 'Legenda',
    extraFrame: 'Dekorativni okvir',
    extraWatermark: 'Vodeni žig',
    titleLabel: 'Tekst naslova',
    downloadPdf: 'Preuzmi PDF',
    print: 'Štampaj',
    pdfHint: 'U dijalogu štampe izaberite „Sačuvaj kao PDF" kao odredište.',
    subtitlePrefix: 'Izvezeno',
    personsWord: 'osoba',
    legendMale: 'Muški',
    legendFemale: 'Ženski',
    legendMain: 'Glavna osoba',
    emptyTree: 'Stablo je prazno — nema šta da se izveze.',
    defaultTitlePrefix: 'Porodica',
  },

  birthdays: {
    birthdaysTitle: 'Rođendani',
    anniversariesTitle: 'Godišnjice braka',
    today: 'Danas! 🎂',
    tomorrow: 'Sutra',
    emptyBirthdays: 'Nema žive osobe sa punim datumom rođenja.',
    emptyAnniversaries: 'Nema aktivnih brakova sa punim datumom venčanja.',
    fullDateNote: 'Prikazuju se samo osobe sa punim datumom rođenja.',
    marriageSuffix: 'braka',
  },

  timeline: {
    birth: 'Rođenje',
    marriage: 'Venčanje',
    partnership: 'Partnerstvo',
    divorce: 'Razvod',
    death: 'Smrt',
    empty: 'Nema događaja sa datumima.',
  },

  kinship: {
    title: 'Kalkulator srodstva',
    personA: 'Osoba A',
    personB: 'Osoba B',
    swap: 'Zameni osobe',
    pickBoth: 'Izaberite dve osobe da biste videli njihovo srodstvo.',
    samePerson: 'Izabrana je ista osoba — izaberite dve različite.',
    pathLabel: 'Putanja srodstva',
    commonAncestor: 'Zajednički predak',
    error: 'Srodstvo nije moglo da se izračuna.',
    selectFirst: 'Izaberite prvu osobu u stablu.',
    selectSecond: 'Izaberite još jednu osobu.',
    openCalculator: 'Otvori kalkulator',
    clear: 'Očisti',
    showConnection: 'Prikaži vezu',
    connectionTitle: 'Veza srodstva',
    connectionMissing: 'Izaberite dve osobe u kalkulatoru da biste prikazali vezu.',
    connectionUnavailable: 'Za ovu vezu nema prikaza u stablu.',
    backToCalculator: 'Nazad na kalkulator',
    /** Dvostruko/višestruko srodstvo. */
    multiNote: 'U srodstvu su po više linija — izaberite koju vezu da prikažete.',
    lineWord: 'linija',
    via: 'preko',
    systemLabel: 'Sistem srodstva',
    systemCivil: 'Rimsko',
    systemCivilShort: 'Rimsko',
    systemCanon: 'Kanonsko',
    systemCanonShort: 'Kanonsko',
    systemCivilBadge: 'rimsko',
    systemCanonBadge: 'kanonsko',
    degreeWord: 'stepen',
    equalLine: 'jednaka linija',
    unequalLine: 'nejednaka linija',
    systemCivilDesc: 'Broji se zbir svih rođenja od obe osobe do zajedničkog pretka (npr. braća su 2. stepen, prvi rođaci 4. stepen).',
    systemCanonDesc: 'Broje se generacije do zajedničkog pretka po dužoj liniji (npr. braća su 1. stepen, prvi rođaci 2. stepen).',
  },

  gedcom: {
    exportTitle: 'Izvoz',
    exportText:
      'Preuzmite celo stablo kao GEDCOM 5.5.1 fajl (.ged) — standardni format za razmenu rodoslovnih podataka.',
    exportButton: 'Preuzmi .ged fajl',
    exportFailed: 'Izvoz nije uspeo.',
    importTitle: 'Uvoz',
    fileLabel: 'GEDCOM fajl (.ged)',
    modeLabel: 'Režim uvoza',
    modeReplace: 'Zameni sve',
    modeReplaceWarning: 'Briše SVE postojeće osobe, brakove i slike pre uvoza. Radnja je nepovratna.',
    modeMerge: 'Dodaj nove',
    modeMergeHint: 'Postojeće osobe se uparuju po GEDCOM oznaci, nove se dodaju.',
    dryRunButton: 'Proveri (probni uvoz)',
    importButton: 'Uvezi',
    confirmReplaceTitle: 'Zameni sve podatke?',
    confirmReplaceText:
      'Uvoz će obrisati sve postojeće osobe, brakove i slike i zameniti ih sadržajem fajla. Ovo ne može da se opozove.',
    confirmReplaceLabel: 'Zameni i uvezi',
    resultDryRunTitle: 'Rezultat probnog uvoza',
    resultTitle: 'Rezultat uvoza',
    personsCreated: 'Novih osoba',
    unionsCreated: 'Novih brakova',
    matched: 'Uparenih postojećih',
    warningsTitle: 'Upozorenja',
    warningTag: 'GEDCOM tag',
    warningCount: 'Broj',
    warningSample: 'Primer',
    noWarnings: 'Bez upozorenja — svi podaci su podržani.',
    imported: 'Uvoz je završen.',
    dryRunDone: 'Probni uvoz je završen — ništa nije upisano.',
  },

  backup: {
    title: 'Potpuna rezervna kopija',
    intro:
      'ZIP sa celom bazom i svim slikama — tačan snimak za vraćanje. Za razliku od GEDCOM-a, uključuje slike i sva interna polja. Dostupno samo administratoru.',
    exportButton: 'Preuzmi rezervnu kopiju (ZIP)',
    exportFailed: 'Izrada rezervne kopije nije uspela.',
    restoreTitle: 'Vraćanje iz kopije',
    restoreHint: 'Učitajte ranije preuzeti ZIP. Ovo BRIŠE sve postojeće osobe, brakove i slike i zamenjuje ih sadržajem kopije.',
    fileLabel: 'Fajl rezervne kopije (.zip)',
    restoreButton: 'Vrati iz kopije',
    confirmTitle: 'Vratiti iz rezervne kopije?',
    confirmText:
      'Vraćanje će obrisati sve trenutne podatke i slike i zameniti ih sadržajem ZIP fajla. Ovo ne može da se opozove.',
    confirmLabel: 'Obriši i vrati',
    restored: 'Vraćanje je završeno.',
    restoreFailed: 'Vraćanje nije uspelo.',
    resultTitle: 'Rezultat vraćanja',
    personsRestored: 'Vraćeno osoba',
    unionsRestored: 'Vraćeno brakova',
    photosRestored: 'Vraćeno slika',
  },

  errors: {
    unauthorized: 'Niste prijavljeni.',
    generic: 'Greška u komunikaciji sa serverom.',
  },

  proposals: {
    kicker: 'PODEŠAVANJA · SARADNJA',
    title: 'Predlozi rođaka',
    intro:
      'Rođak sa pozivnim linkom radi u aplikaciji kao i vi — dodaje, menja i briše osobe, brakove i slike — ali sve ostaje u grani linka dok izmene ne pregledate i spojite u stablo.',
    settingsHint: 'Pozivni linkovi za rođake i pregled njihovih izmena pre spajanja u stablo.',
    settingsLink: 'Predlozi i pozivni linkovi',
    loadFailed: 'Podaci nisu mogli da se učitaju.',
    // Pozivni linkovi
    newToken: 'Novi pozivni link',
    tokenIntro:
      'Svi koji otvore isti link rade na istoj grani i vide izmene jedni drugih — za odvojene grane napravite više linkova. Link možete opozvati u svakom trenutku.',
    tokenLabel: 'Za koga je link',
    tokenLabelPlaceholder: 'npr. Rođaci iz Niša',
    tokenDuration: 'Važi',
    tokenDays: 'dana',
    createToken: 'Napravi link',
    tokenCreatedTitle: 'Link je napravljen',
    tokenCreatedText: 'Pošaljite ovaj link rođacima. Važi do',
    tokensTitle: 'Linkovi i grane',
    noTokens: 'Još nema pozivnih linkova.',
    tokenActive: 'Aktivan',
    tokenExpired: 'Istekao',
    tokenSubmitted: 'Poslato na odobrenje',
    tokenCreated: 'Napravljen',
    tokenExpires: 'Važi do',
    submittedBy: 'Poslao/la',
    review: 'Pregledaj',
    copyLink: 'Kopiraj link',
    copied: 'Link je kopiran.',
    copyFailed: 'Kopiranje nije uspelo — označite link i kopirajte ga ručno.',
    revoke: 'Opozovi',
    confirmRevokeTitle: 'Opozvati link?',
    confirmRevokeText:
      'Link odmah prestaje da važi i trajno se briše zajedno sa svojom granom — nespojene izmene se gube.',
    confirmRevokeChanges: 'Nespojenih izmena:',
    revoked: 'Link je opozvan i obrisan.',
    // Pregled grane
    backToLinks: 'Nazad na linkove',
    reviewKicker: 'PREGLED GRANE',
    reviewIntro:
      'Izaberite izmene koje spajate u stablo. Izmene u konfliktu nisu unapred izabrane — proverite ih. Odbačene izmene nestaju iz grane.',
    emptyChanges: 'U ovoj grani nema izmena za pregled.',
    selectAll: 'Izaberi sve',
    selectNone: 'Poništi izbor',
    selectedCount: 'izabrano',
    mergeSelected: 'Spoji izabrano',
    discardSelected: 'Odbaci izabrano',
    brokenSelected: 'Izbor sadrži izmene koje ne mogu da se primene — odbacite ih ili ih isključite iz izbora.',
    confirmMergeTitle: 'Spojiti izabrane izmene u stablo?',
    confirmMergeText: 'U glavno stablo se trajno upisuje:',
    confirmMergeLabel: 'Spoji u stablo',
    merged: 'Spojeno u stablo:',
    confirmDiscardTitle: 'Odbaciti izabrane izmene?',
    confirmDiscardText: 'Iz grane se trajno uklanja (sa izmenama koje od njih zavise):',
    discarded: 'Izmene su odbačene.',
  },

  branch: {
    banner: 'Režim predloga',
    exit: 'Izađi',
    exited: 'Izašli ste iz režima predloga.',
    closed: 'Pozivni link je istekao ili je opozvan.',
    changeForms: ['izmena', 'izmene', 'izmena'],
    // Ulazak preko linka
    enterKicker: 'POZIV ZA SARADNJU',
    enterIntro:
      'Možete da dodajete, menjate i brišete osobe, brakove i slike kao u pravom stablu. Sve izmene ostaju u grani ovog linka dok ih administrator ne pregleda i spoji.',
    enterShared: 'Svi koji imaju ovaj link rade na istoj grani i vide izmene jedni drugih.',
    validUntil: 'Link važi do',
    authorName: 'Vaše ime i prezime',
    authorNamePlaceholder: 'npr. Petar Petrović',
    authorHint: 'Ime se prikazuje administratoru uz vaše izmene.',
    enter: 'Uđi u režim predloga',
    invalidTitle: 'Link ne važi',
    invalidText: 'Pozivni link je istekao ili je opozvan. Zamolite osobu koja vam ga je poslala za novi.',
    loadFailed: 'Link nije mogao da se proveri. Pokušajte ponovo.',
    // Izmene u grani
    kicker: 'REŽIM PREDLOGA',
    changesTitle: 'Izmene u grani',
    changesIntro:
      'Ovo su izmene koje čekaju pregled administratora. Kada završite, pošaljite ih na odobrenje.',
    submitTitle: 'Slanje na odobrenje',
    submitNote: 'Poruka administratoru (opciono)',
    submitNotePlaceholder: 'npr. odakle su podaci, šta još treba proveriti…',
    submit: 'Pošalji na odobrenje',
    submitted: 'Izmene su poslate na odobrenje.',
    submittedAt: 'Poslato na odobrenje',
    submitAgainHint: 'Možete da nastavite sa izmenama — administrator vidi trenutno stanje grane.',
    emptyChanges: 'U grani još nema izmena. Vratite se na stablo i počnite.',
    discardSelected: 'Poništi izabrano',
    confirmDiscardTitle: 'Poništiti izabrane izmene?',
    confirmDiscardText: 'Izmene se uklanjaju iz grane i za sve koji koriste ovaj link:',
    discarded: 'Izmene su poništene.',
    // Prikaz izmena
    actionPersonCreate: 'Nova osoba',
    actionPersonUpdate: 'Izmena osobe',
    actionPersonDelete: 'Brisanje osobe',
    actionUnionCreate: 'Novi brak',
    actionUnionUpdate: 'Izmena braka',
    actionUnionDelete: 'Brisanje braka',
    statusConflict: 'Konflikt',
    statusBroken: 'Ne može da se primeni',
    colField: 'Polje',
    colBefore: 'Bilo',
    colAfter: 'Postaje',
    colValue: 'Vrednost',
    nowInTree: 'U stablu sada',
    dependsOn: 'Zavisi od',
    familyHead: 'Glava porodice',
    partner: 'Partner',
    yes: 'Da',
    no: 'Ne',
  },
} as const;
